#Autor original Ricardo Moya https://github.com/RicardoMoya/FootballMatchesDataSet

# De la web: http://www.bdfutbol.com. Para el historico de partidos de futbol
URLS = {1:"http://www.bdfutbol.com/es/t/t%s.html", 2:"http://www.bdfutbol.com/es/t/t%s2a.html"}
TEMPORADAS = ["2020-21", "2019-20", "2018-19", "2017-18", "2016-17", "2015-16", "2014-15", "2013-14", "2012-13", "2011-12", "2010-11", "2009-10", "2008-09", "2007-08", "2006-07", "2005-06", "2004-05", "2003-04", "2002-03", "2001-02", "2000-01", "1999-00", "1998-99", "1997-98", "1996-97", "1995-96", "1994-95", "1993-94", "1992-93", "1991-92", "1990-91", "1989-90", "1988-89", "1987-88", "1986-87", "1985-86", "1984-85", "1983-84", "1982-83", "1981-82", "1980-81", "1979-80", "1978-79", "1977-78", "1976-77", "1975-76", "1974-75", "1973-74", "1972-73", "1971-72", "1970-71"]

NAMES_CORRECTION = {}

NAMES_CORRECTION = {"Alavés": "Alavés",
                    "Athletic Club": "Athletic Club",
                    "Atlético de Madrid": "Atlético de Madrid",
                    "Barcelona": "Barcelona",
                    "Betis": "Betis",
                    "Cádiz": "Cádiz",
                    "Celta de Vigo": "Celta de Vigo",
                    "Eibar": "Eibar",
                    "Elche": "Elche",
                    "Getafe": "Getafe",
                    "Granada": "Granada",
                    "Huesca": "Huesca",
                    "Levante": "Levante",
                    "Osasuna": "Osasuna",
                    "Real Sociedad": "Real Sociedad",
                    "Real Madrid": "Real Madrid",
                    "Sevilla": "Sevilla",
                    "Valladolid": "Valladolid",
                    "Valencia": "Valencia",
                    "Villarreal": "Villarreal",
                    "Albacete": "Albacete",
                    "Alcorcón": "Alcorcón",
                    "Almería": "Almería",
                    "Castellón": "Castellón",
                    "Espanyol": "Espanyol",
                    "FC Cartagena": "FC Cartagena",
                    "Fuenlabrada": "Fuenlabrada",
                    "Girona": "Girona",
                    "Las Palmas": "Las Palmas",
                    "Leganés": "Leganés",
                    "Lugo": "Lugo",
                    "Mallorca": "Mallorca",
                    "Málaga": "Málaga",
                    "Mirandés": "Mirandés",
                    "Oviedo": "Oviedo",
                    "Ponferradina": "Ponferradina",
                    "Rayo Vallecano": "Rayo Vallecano",
                    "Sabadell": "Sabadell",
                    "Sporting de Gijón": "Sporting de Gijón",
                    "Tenerife": "Tenerife",
                    "UD Logroñés": "UD Logroñés",
                    "Zaragoza": "Zaragoza",
                    "Deportivo de La Coruña": "Deportivo de La Coruña",
                    "Extremadura UD": "Extremadura UD",
                    "Numancia": "Numancia",
                    "Racing de Santander": "Racing de Santander",
                    "Córdoba": "Córdoba",
                    "Gimnàstic de Tarragona": "Gimnàstic de Tarragona",
                    "Rayo Majadahonda": "Rayo Majadahonda",
                    "Reus": "Reus",
                    "Barcelona B": "Barcelona B",
                    "Cultural Leonesa": "Cultural Leonesa",
                    "Lorca FC": "Lorca FC",
                    "Sevilla Atlético": "Sevilla Atlético",
                    "UCAM Murcia": "UCAM Murcia",
                    "Bilbao Athletic": "Athletic Club",
                    "Llagostera": "Llagostera",
                    "Recreativo de Huelva": "Recreativo de Huelva",
                    "Hércules": "Hércules",
                    "Jaén": "Jaén",
                    "Murcia": "Murcia",
                    "Real Madrid Castilla": "Real Madrid Castilla",
                    "Guadalajara": "Guadalajara",
                    "Xerez": "Xerez",
                    "Alcoyano": "Alcoyano",
                    "Villarreal B": "Villarreal B",
                    "Salamanca": "Salamanca",
                    "Real Unión": "Real Unión",
                    "Alicante": "Alicante",
                    "Granada 74": "Granada 74",
                    "Polideportivo Ejido": "Polideportivo Ejido",
                    "Racing de Ferrol": "Racing de Ferrol",
                    "Ciudad de Murcia": "Ciudad de Murcia",
                    "Lorca Deportiva": "Lorca Deportiva",
                    "Vecindario": "Vecindario",
                    "Lleida": "Lleida",
                    "Málaga B": "Málaga B",
                    "Pontevedra": "Pontevedra",
                    "Terrassa": "Terrassa",
                    "Algeciras": "Algeciras",
                    "Badajoz": "Badajoz",
                    "Compostela": "Compostela",
                    "Burgos CF": "Burgos CF",
                    "Extremadura": "Extremadura",
                    "Universidad de Las Palmas": "Universidad de Las Palmas",
                    "Atlético de Madrid B": "Atlético de Madrid B",
                    "Logroñés": "UD Logroñés",
                    "Mérida": "Mérida",
                    "Toledo": "Toledo",
                    "Mallorca B": "Mallorca B",
                    "Ourense": "Ourense",
                    "Écija": "Écija",
                    "Orense": "Ourense",
                    "Real Madrid B": "Real Madrid Castilla",
                    "Athletic Club B": "Athletic Club B",
                    "Atlético Marbella": "Atlético Marbella",
                    "Sestao": "Sestao",
                    "Español": "Espanyol",
                    "Palamós": "Palamós",
                    "Real Burgos": "Burgos CF",
                    "Figueres": "Figueres",
                    "Avilés Industrial": "Avilés Industrial",
                    "CD Málaga": "Málaga",
                    "Orihuela": "Orihuela",
                    "Atlético Madrileño": "Atlético de Madrid B",
                    "Castilla": "Real Madrid Castilla",
                    "Alzira": "Alzira",
                    "Barcelona Atlético": "Barcelona B",
                    "Mollerussa": "Mollerussa",
                    "Cartagena": "FC Cartagena",
                    "Deportivo Aragón": "Deportivo Aragón",
                    "Calvo Sotelo": "Calvo Sotelo",
                    "Lorca": "Lorca",
                    "Linares CF": "Linares CF",
                    "Palencia CF": "Palencia CF",
                    "AD Almería": "Almería",
                    "Burgos": "Burgos CF",
                    "Getafe Deportivo": "Getafe",
                    "AD Ceuta": "AD Ceuta",
                    "Baracaldo": "Baracaldo",
                    "Gimnástico de Tarragona": "Gimnàstic de Tarragona",
                    "Tarrasa": "Tarrasa",
                    "San Andrés": "San Andrés",
                    "Ensidesa": "Ensidesa",
                    "Mestalla": "Mestalla",
                    "Atlético de Bilbao": "Athletic Club",
                    "Ferrol": "Racing de Ferrol",
                    "Langreo": "Langreo",
                    "Santander": "Racing de Santander",
                    "Gijón": "Sporting de Gijón",
                    "Moscardó": "Moscardó",
                    "Onteniente": "Onteniente"
                }